### ISSUE TITLE
Deprecated package dependency in use

### ISSUE THREAD

**Issue by kontact00** [thomasdavis/pinjs#14]
Hi,
Are there any plans to update the deprecated package depenencies?

node API which has the following issues:
warning pinjs > request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
warning pinjs > request > hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning pinjs > request > hawk > cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning pinjs > request > hawk > sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning pinjs > request > hawk > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning pinjs > request > hawk > sntp > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning pinjs > request > hawk > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning pinjs > request > hawk > cryptiles > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning pinjs > request > hawk > boom > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

**Comment by montdidier** [comment]
Should be addressed by https://github.com/thomasdavis/pinjs/pull/15

**Comment by montdidier** [comment]
@kontact00 what version of node are you using?

**Comment by kontact00** [comment]
Im running 12.16.1 on AWS. (64bit Amazon Linux 2018.03 v4.14.1)

**Comment by montdidier** [comment]
This update should work for you then.

**Comment by montdidier** [comment]
@kontact00 This has been released.
