### ISSUE TITLE
What happened to the retrieveCards

### ISSUE THREAD

**Issue by kontact00** [thomasdavis/pinjs#20]
Hi,
I've just implemented the latest and now I cant see the following in the pin.js

 this.retrieveCards = function (token, callback) {
    var url = options.url + '/1/customers/' + token + '/cards';
    var req = request.get({url: url, json: true}, callback);
    generateRequest(req);
  };

I can't see an alternative in the file to use. I would try and add it in myself but I'm not comfortable that I wont break it. 

I've tried using the getRecipientData but with the Node Version I'm on I'm now getting

Node Version is 12.16.2

> (node:22520) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
>     at /var/app/current/node_modules/pinjs/lib/pin.js:73:70
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:22520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:22520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:22520) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'body' of undefined
>     at /var/app/current/node_modules/pinjs/lib/pin.js:73:70
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:22520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by montdidier** [comment]
I am not sure it ever existed previously. [Release 1.1.1](https://www.npmjs.com/package/pinjs) now has retrieveCustomerCards though.

**Comment by montdidier** [comment]
@kontact00 [Release 1.1.3](https://www.npmjs.com/package/pinjs) should fix this exception you were experiencing.

**Comment by kontact00** [comment]
Thanks guys.
